[build]
  bin = "./bin/stats-tracker"
  cmd = "make build"
  delay = 1000
  exclude_dir = ["node_modules", "bin"]
  exclude_file = ["assets/js/main.min.js", "assets/css/output.css"]
  exclude_regex = ["_test.go", "_templ.go"]
  include_ext = ["go", "js", "templ", "css"]
  stop_on_error = false

[misc]
  clean_on_exit = true
